version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    restart: always
    environment:
      - VITE_API_URL=http://ecommerce-backend:5000/api
      - VITE_WS_URL=ws://ecommerce-backend:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge